### PR TITLE
Update dragonfly-google_data_store.gemspec

### PR DESCRIPTION
**Pull request by krtschmr**
https://github.com/GoogleCloudPlatform/google-cloud-ruby/tree/master/google-cloud-storage

i don't see any 1.0 matching

### CODE REVIEW

**Comment by tomasc** [comment]
@wtag @krtschmr is this gem maintained? Do you need any help?

**Comment by luxflux** [comment]
Sorry, I somehow totally missed this PR... 

I'm not sure about this change. It should actually allow any kind of version from https://rubygems.org/gems/google-cloud-storage - why is it needed for you?

**Comment by krtschmr** [comment]
can't remember anymore. it's 4 years ago :-)

but forcing versions in Gemfile isn't a bad idea at all

**Comment by luxflux** [comment]
> but forcing versions in Gemfile isn't a bad idea at all

I don't quite understand. IMHO a library should specify the version it's compatible with. If google-cloud-storage follows semver, we should be safe to keep `~> 1.0`. If your app then needs a specific version (e.g. 1.1), you can still do that in `Gemfile` w/o this PR.

**Comment by krtschmr** [comment]
i can't remember anything here. let's close this :-)

**Pull request closed without merging**
